
var formulario=null;var CEP={};CEP.actualizaUICriterio=function(){var tCriterio=$("select[name='tipoCriterio']").val();if(tCriterio=='T'){$("input[name='criterio']").attr('placeholder','Clave de rastreo');$("input[name='criterio']").attr('maxlength','30');$("input[name='criterio']").attr('onkeypress','writeValidCharacterClaveRastreo(event)');$("input[name='criterio']").attr('title','Es un identificador de hasta 30 posiciones alfanuméricas que la institución le proporciona al usuario al momento en que se instruye el pago.');$("label[for='input_criterio']").html("Clave de rastreo");}else{$("input[name='criterio']").attr('placeholder','Número de referencia');$("input[name='criterio']").attr('maxlength','7');$("input[name='criterio']").attr('onkeypress','onlyWriteNumber(event);');$("input[name='criterio']").attr('title','Es un número de identificación de hasta siete posiciones que el usuario selecciona al momento de instruir su pago');$("label[for='input_criterio']").html("Número de referencia");}
$("#input_criterio").val("");}
CEP.getFechaFormato=function(sFecha){var tkns=sFecha.split("-");return tkns[2]+""+tkns[1]+""+tkns[0];}
CEP.formatFecha=function(sFecha){return sFecha.substring(6)+"-"+sFecha.substring(4,6)+"-"+sFecha.substring(0,4);}
CEP.init=function(calendarMinDate,callback,fechaInicio24_7,ultimaFechaVentana){$("#btn_Responsabilidades").on('click',mostrarResponsabilidades);if(((typeof isBlackberry)!="undefined")){$("span.appName").html("CEP");formulario=$("form[action='valida.do']");showLoader=function(){};hideLoader=function(){};}
$("select[name='tipoCriterio']").on('change',CEP.actualizaUICriterio);$("#input_fecha").datepicker({'changeYear':true,'changeMonth':true,'minDate':new Date(calendarMinDate),'monthNamesShort':$.datepicker.regional["es"].monthNames,'maxDate':new Date(),'dateFormat':"dd-mm-yy",'beforeShowDay':function(date){var d=jQuery.datepicker.formatDate('yymmdd',date);var clase="";if(d<ultimaFechaVentana){clase="fueraVentana"}
if(d<=fechaInicio24_7){return[$.datepicker.noWeekends(date)[0],clase];}else{return[true,clase];}}});$("#input_fecha").datepicker($.datepicker.regional["es"]);$("#input_fecha").datepicker("setDate",new Date());var expr=new RegExp('[0-3][0-9][-][0-1][0-9][-][0-9]{4}$');$("[name='fecha']").on('change',function(){var valor=$("[name='fecha']").val();if(valor==undefined||expr.exec(valor)==null){showFloatingHTML("Debe ingresar una fecha válida");return;}
var fechaSeleccionada=CEP.getFechaFormato(valor);if(fechaSeleccionada<ultimaFechaVentana){$("#msg_fecha").removeClass("hidden");}else{$("#msg_fecha").addClass("hidden");}
$.ajax({url:"instituciones.do",data:{fecha:valor},beforeSend:function(xhr){showLoader();},success:function(resp){var instituciones=resp.instituciones;var instMispei=resp.institucionesMISPEI;if(instMispei==undefined||instituciones==undefined){hideLoader();showFloatingHTML("No se pudo recuperar el catálogo de instituciones para la fecha solicitada. Intente nuevamente más tarde.");return;}
var cbEmisor=$("select[name='emisor']"),cbReceptor=$("select[name='receptor']");cbEmisor.empty();cbReceptor.empty();for(var i=0;i<instMispei.length;i++){var elemento='<option value="'+instMispei[i][0]+'" >'+instMispei[i][1]+'</option>';cbEmisor.append(elemento);}
for(var i=0;i<instituciones.length;i++){var elemento='<option value="'+instituciones[i][0]+'" >'+instituciones[i][1]+'</option>';cbReceptor.append(elemento);}
setTimeout(function(){if(instituciones.length>=2){$("select[name='receptor']").val(instituciones[1][0]);if(callbackPostFecha!=undefined&&callbackPostFecha!=null){callbackPostFecha();callbackPostFecha=null;}}
hideLoader();},500);},error:function(){showFloatingHTML("Ocurrió un error. Recargue la página e intente nuevamente.");}});});if(callback!=null){callback();callback=null;return;}
$("[name='fecha']").trigger("change");CEP.estableceEventosBotones();}
CEP.estableceEventosBotones=function(){$("#btn_ReloadCaptcha").on('click',function(){CEP.recargaCaptcha();});$("#btn_Limpiar").on('click',function(){limpiaFormulario();});var btn_Descargar=$("#btn_Descargar");var btn_Consultar=$("#btn_Consultar");function setClick(o,n){o.on('click',function(){verificaFormulario(n);});}
setClick(btn_Descargar,1);setClick(btn_Consultar,0);$("#fConsulta").on('input',validaActivacionBotones);}
CEP.recargaCaptcha=function(){$("#img_captcha").attr('src','stickyImg?b_capt='+new Date().getMilliseconds());$("input[name='captcha']").val("");}
CEP.muestraCaptcha=function(){var showCaptchaDiv=$("input[name='varHideCaptcha']").val();if(showCaptchaDiv==="true"){$("#captchaImage").addClass("oculta");$("#captchaInput").addClass("oculta");}
if(showCaptchaDiv==="false"){$(".entrada").removeClass("oculta");}}
function validaEntradasVacias(campos,mensajeError){if(campos.length==0){showFloatingHTML(mensajeError);return true;}
for(var i=0;i<campos.length;i++){if(campos[i].value==""||campos[i].value.trim()==""){showFloatingHTML(mensajeError);return true;}}
return false;}
function validaCampoVacio(nombreCampo,mensajeError){return validaEntradasVacias($("input[name='"+nombreCampo+"']"),mensajeError);}
function validaComboVacio(nombreCampo,mensajeError){return validaEntradasVacias($("select[name='"+nombreCampo+"']"),mensajeError);}
function validaIguales(nombreCampo1,nombreCampo2){var campos1=$("select[name='"+nombreCampo1+"']");var campos2=$("select[name='"+nombreCampo2+"']");for(var i=0;i<campos1.length;i++){if(campos1[i].value==campos2[i].value){showFloatingHTML("El banco emisor y el banco receptor son iguales. Favor de verificar.");return true;}}
return false;}
function validaCriterio(){var campo=$("input[name='criterio']").val().trim();$("input[name='criterio']").val(campo);var tipoCriterio=$("select[name='tipoCriterio']").val();if(campo.length<1){showFloatingHTML(""+obtieneTexto(tipoCriterio)+". Favor de verificar.");showFloatingHTML(""+obtieneTexto(tipoCriterio)+". Favor de verificar.");return false;}else if(tipoCriterio=="T"&&campo.length>30){showFloatingHTML("La longitud de la clave de rastreo no debe ser mayor a 30 caracteres.");return false;}else if(tipoCriterio=="R"&&campo.length>7){showFloatingHTML("N\u00famero de referencia inv\u00e1lido. Debe tener un m\u00e1ximo de 7 d\u00edgitos.");return false;}else if(tipoCriterio=="R"&&!regexpReferencia.test(campo)){showFloatingHTML("N\u00famero de referencia inv\u00e1lido. Favor de verificar.");return false;}
return true;}
function obtieneTexto(tCriterio){if(tCriterio=='R'){return("El n\u00famero de referencia es inv\u00e1lido");}else{return("La clave de rastreo es inv\u00e1lida");}}
function validaCuenta(){var campo=reemplazaTodo($("input[name='cuenta']").val()," ","");$("input[name='cuenta']").val(campo);return regexpCuenta.test(campo);}
function reemplazaTodo(cadena,cadenaABuscar,sustituto){return cadena.replace(new RegExp(cadenaABuscar,'g'),sustituto);}
var regexpReferencia=new RegExp("^[0-9]{0,7}$");var regexpMonto=new RegExp("^([0-9]*\.{0,1}[0-9]{0,2})$");var regexpCuenta=new RegExp("^[0-9]{1,20}$");function verificaFormulario(tipo){var criterioBusqueda=$("#input_criterio").val();var cuenta=$("#input_cuenta").val();var monto=$("#input_monto").val();var ic=$("#input_captcha").val();if(tipo==0){if(criterioBusqueda.length==0){$("#input_criterio").attr('style','border:  1px solid red; background: #FFFFCC;');$("#input_criterio").on('focus');return false;}else{$("#input_criterio").removeAttr('style');}
if(ic.length>5){$("#input_captcha").attr('style','border:  1px solid red; background: #FFFFCC;');$("#input_captcha").on('focus');return false;}else{$("#input_captcha").removeAttr('style');}}else if(tipo==1){if(criterioBusqueda.length==0){$("#input_criterio").attr('style','border:  1px solid red; background: #FFFFCC;');$("#input_criterio").on('focus');return false;}else{$("#input_criterio").removeAttr('style');}
if(cuenta.length==0){$("#input_cuenta").attr('style','border:  1px solid red; background: #FFFFCC;');$("#input_cuenta").on('focus');return false;}else{$("#input_cuenta").removeAttr('style');}
if(monto.length==0){$("#input_monto").attr('style','border:  1px solid red; background: #FFFFCC;');$("#input_monto").on('focus');return false;}else{$("#input_monto").removeAttr('style');}
if(ic.length>5){$("#input_captcha").attr('style','border:  1px solid red; background: #FFFFCC;');$("#input_captcha").on('focus');return false;}else{$("#input_captcha").removeAttr('style');}}
if(!validateDate()){showFloatingHTML("Fecha incorrecta, error en el formato, por favor verifiquelo");return false;}
if(!validateClaveRastreo()){showFloatingHTML("La clave de rastreo porporcionada no es valida, por favor verifiquelo");return false;}
if(validaComboVacio('emisor','El banco emisor es inv\u00e1lido. Favor de verificar.')){return false;}
if(validaComboVacio('receptor','El banco receptor es inv\u00e1lido. Favor de verificar.')){return false;}
if(validaCampoVacio('criterio','El criterio de consulta es inv\u00e1lido. Favor de verificar.')){return false;}
if(tipo===1&&validaCampoVacio('cuenta','El n\u00famero de cuenta es inv\u00e1lido. Favor de verificar. vacio')){return false;}
if(tipo===1&&validaCampoVacio('monto','El monto de la operaci\u00f3n es inv\u00e1lido. Favor de verificar.')){return false;}
if(tipo==1&&!validateMonto()){showFloatingHTML('El monto de la operaci\u00f3n es inv\u00e1lido. Favor de verificar.');return false;}
if(validaIguales('emisor','receptor')){return false;}
if(!validaCriterio()){return false;}
if(tipo==1&&!validaCuenta()){showFloatingHTML('El n\u00famero de cuenta es inv\u00e1lido. Favor de verificar. no vacio');return false;}
$("input[name='monto']").val(reemplazaTodo($("input[name='monto']").val(),",",""));$("input[name='monto']").val(reemplazaTodo($("input[name='monto']").val()," ",""));if(!regexpMonto.test($("input[name='monto']").val())){showFloatingHTML('El monto de la operaci\u00f3n es inv\u00e1lido. Favor de verificar.');return false;}
if(!($(".entrada").hasClass("oculta"))&&validaCampoVacio('captcha','El texto de la imagen de seguridad no ha sido ingresado. Favor de verificar.')){return false;}
$("input[name='tipoConsulta']").val(tipo);if(formulario!=null){formulario.submit();}else{descargaFormatos();$("#btn_Descargar").attr("style","cursor:default;");$("#btn_Consultar").attr("style","cursor:default;");$("#btn_Descargar").addClass("disabled");$("#btn_Consultar").addClass("disabled");}
return false;}
function validaActivacionBotones(){var ic=$("#input_captcha").val();function tieneInfo(campo){return!($(campo).val().trim()=="");}
if(tieneInfo("input[name='criterio']")&&tieneInfo("select[name='emisor']")&&tieneInfo("select[name='receptor']")&&((!($(".entrada").hasClass("oculta"))&&ic.length===5)||$(".entrada").hasClass("oculta"))){$("#btn_Consultar").removeClass("disabled");$("#btn_Consultar").removeAttr('style');if(tieneInfo("input[name='monto']")&&tieneInfo("input[name='cuenta']")){$("#btn_Descargar").removeClass("disabled");$("#btn_Descargar").removeAttr('style');}else{$("#btn_Descargar").addClass("disabled");}}else{$("#btn_Consultar").addClass("disabled");$("#btn_Descargar").addClass("disabled");}}
function limpiaFormulario(){$("select[name='tipoCriterio']").prop('selectedIndex',0).trigger("change");$("input[name='criterio']").val('');$("input[name='cuenta']").val('');$("input[name='receptorParticipante']")[0].checked=false;$("input[name='monto']").val('');$("input[name='captcha']").val('');$("select[name='emisor']").prop('selectedIndex',0);$("select[name='receptor']").prop('selectedIndex',1);validaActivacionBotones();}
function descargaFormatos(){var objInfoConsulta={};objInfoConsulta.tipoCriterio=$("select[name='tipoCriterio']").val().trim();objInfoConsulta.fecha=$("[name='fecha']").val().trim();objInfoConsulta.criterio=$("input[name='criterio']").val().trim();objInfoConsulta.emisor=$("select[name='emisor']").val().trim();objInfoConsulta.receptor=$("select[name='receptor']").val().trim();objInfoConsulta.cuenta=$("input[name='cuenta']").val().trim();objInfoConsulta.receptorParticipante=$("input[name='receptorParticipante']")[0].value.trim();objInfoConsulta.monto=$("input[name='monto']").val().trim();validateBanks();if($("input[name='captcha']").length===1){objInfoConsulta.captcha=$("input[name='captcha']").val().trim();}else{objInfoConsulta.captcha='c';}
objInfoConsulta.tipoConsulta=$("input[name='tipoConsulta']").val().trim();showLoader(function(){var tOut=setTimeout(function(){var msg="La consulta  puede tardar un poco m&aacute;s de lo normal debido a que estamos buscando en el repositorio de informaci&oacute;n hist&oacute;rica.<br/> Espere un momento.";modificaMensajeLoader(msg,function(){centerInWindow("#divValidacionPertenencia div.gif-loader");});},25000);$.ajax({url:"valida.do",type:"POST",data:objInfoConsulta,success:function(data){clearTimeout(tOut);hideLoader(function(){if(data.indexOf("meta:stats=ERR")!=-1){showFloatingHTML('No se ingres\u00f3 correctamente la informaci\u00f3n necesaria para validar la operaci\u00f3n. Intente nuevamente.');}else{if(data.indexOf("ERR")==-1){delete objInfoConsulta.captcha;CEP.Historico.almacenaEnHistorico(objInfoConsulta);}
showFloatingHTML(data);}});CEP.recargaCaptcha();},error:function(jqXHR){clearTimeout(tOut);hideLoader(function(){if(jqXHR.responseText!=undefined&&jqXHR.responseText!=="")
showFloatingHTML(jqXHR.responseText);else
showFloatingHTML("Ocurri&oacute; un error en la consulta. Intente nuevamente m&aacute;s tarde.");});CEP.recargaCaptcha();}});});}
function confirmaCuenta(){var cuenta=$("input[name='cuenta_depura']").val().trim();if(cuenta==""){showFloatingHTML('Ingrese la cuenta CLABE que origin\u00f3 el pago.');return false;}
showLoader(function(){var tOut=setTimeout(function(){modificaMensajeLoader("La consulta de operaciones antiguas puede tardar un poco más de lo normal.<br/> Espere un momento.",function(){centerInWindow("#divValidacionPertenencia div.gif-loader");});},15000);$.ajax({url:"depura.do",type:"POST",data:{'cuenta':cuenta},success:function(data){clearTimeout(tOut);hideLoader(function(){showFloatingHTML(data);});},error:function(jqXHR){clearTimeout(tOut);hideLoader(function(){showFloatingHTML(jqXHR.responseText);CEP.recargaCaptcha();});}});});return false;}
function mostrarResponsabilidades(){$.ajax({url:"obligaciones.do",type:"GET",success:function(data){showFloatingHTML(data);}});}
function modificaMensajeLoader(msg,cb){if(msg===undefined){msg="Cargando";}
$("#msg-loader").html(msg);runCallback(cb);}
function showLoader(callback,msg){modificaMensajeLoader(msg,function(){var div=$("#divValidacionPertenencia div.gif-loader");$("#pagewidth").addClass("blurred");$("#divValidacionPertenencia").fadeIn(function(){div.fadeIn('fast',function(){centerInWindow("#divValidacionPertenencia div.gif-loader");runCallback(callback);});});});}
function runCallback(callback){if(!((typeof callback)==='undefined')){callback();}}
function hideLoader(callback){if((typeof callback)==='undefined'){$("#pagewidth").removeClass("blurred");$("#divValidacionPertenencia").fadeOut("slow",function(){$("#divValidacionPertenencia div.gif-loader").hide();});}else{$("#divValidacionPertenencia div.gif-loader").fadeOut('fast',callback);}}
function setEventIfExists(selector,event,fx){var obj=$(selector);if(obj.length>0){obj.on(event,fx);}}
function showFloatingHTML(data,callback){$("#pagewidth").addClass("blurred");if(data.search("<")==-1){$("#divValidacionPertenencia div.msg-banxico div.contenido").html("<div class='bg-banxico title-bar'><i class='icono-header icon-warning3'></i><strong>Error</strong></div><p style='padding:10px; max-width:500px; text-align:center;'>"+data+"</p>");}else{$("#divValidacionPertenencia div.msg-banxico div.contenido").html(data);CEP.muestraCaptcha();}
$("#divValidacionPertenencia").fadeIn(function(){centerInWindow('#divValidacionPertenencia div.msg-banxico');});$("#divValidacionPertenencia div.msg-banxico").fadeIn();setEventIfExists("#btnEstadosPago","click",mostrarDetalleEstadosMISPEI);setTimeout(function(){centerInWindow('#divValidacionPertenencia div.msg-banxico');},300);setEventIfExists("#btnConfirmacionCuenta","click",confirmaCuenta);$("#btnCerrar").on('click',function(){$("#pagewidth").removeClass("blurred");$("#divValidacionPertenencia").fadeOut(function(){$("#divValidacionPertenencia div.msg-banxico").hide();if(callback!=null&&callback!=undefined){callback();}});});}
function centerInWindow(id){var div=$(id);div.animate({left:($(window).width()-div.outerWidth())/2,top:($(window).height()-div.outerHeight())/2},'100');}
function mostrarDetalleEstadosMISPEI(){$(".descripcion").toggleClass("oculta");}
$(document).ready(function(){window.scrollTo(0,1);CEP.init(initData.minDate,callbackInitFx,initData.fIni247,initData.ultimaFechaVentana);});function validateBanks(){if($("#input_emisor").val()==undefined&&$("#input_receptor").val()==undefined){showFloatingHTML("Es necesario ingresar tanto el banco receptor como el banco emisor");return false;}else{if($("#input_emisor").val()==$("#input_receptor").val()){showFloatingHTML("Los bancos deben de ser diferentes");return false;}
return true;}}
function messageAlert(message){bootbox.alert({size:"large",title:"<div style='padding-top: 15px'><i class='icono-header icon-warning3'></i><strong>Error</strong></div>",message:"<div style='margin-bottom: 40px;'><center>"+message+"</center></div>",callback:function(){}});};

CEP.Historico={};var nop=function(){};CEP.Historico.muestraHistorico=nop;CEP.Historico.almacenaEnHistorico=nop;
